title: Emprego Público - Dados Abertos
author:
  name: Emprego Público
#  email: your-email@domain.com

url: "https://empregopublico.github.io/" # the base hostname & protocol for your site

plugins:
  - jekyll-feed
  - jekyll-sitemap  

feed:
  posts_limit: 1000
  path: /rss.xml
  